# Generated by Django 6.0.4 on 2026-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Айди категории')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Айди пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=100, verbose_name='Почта пользователя')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Пароль')),
                ('avatar_path', models.CharField(max_length=255, verbose_name='Путь до аватара')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
        ),
    ]
