# Generated by Django 6.0.4 on 2026-05-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plapp', '0002_finance_categories_remove_task_categories_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='finance_categories',
            options={'verbose_name': 'Категория финансов', 'verbose_name_plural': 'Категории финансов'},
        ),
        migrations.AlterModelOptions(
            name='finances',
            options={'verbose_name': 'Финансовая запись', 'verbose_name_plural': 'Финансы'},
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterModelOptions(
            name='habit_logs',
            options={'verbose_name': 'Лог привычки', 'verbose_name_plural': 'Логи привычек'},
        ),
        migrations.AlterModelOptions(
            name='habits',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterModelOptions(
            name='task_categories',
            options={'verbose_name': 'Категория задачи', 'verbose_name_plural': 'Категории задач'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='favorites',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.tasks', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='finance_categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='finance_categories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='finance_categories',
            name='type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.finance_categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='operation_date',
            field=models.DateField(verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('achieved', 'Достигнута')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='target_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='habit_logs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='habit_logs',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.habits', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='habit_logs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habit_logs',
            name='log_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='habit_logs',
            name='status',
            field=models.CharField(choices=[('done', 'Выполнено'), ('skipped', 'Пропущено')], default='done', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=10, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plapp.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='task_categories',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='task_categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task_categories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plapp.task_categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plapp.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
