# Generated by Django 6.0.4 on 2026-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plapp', '0003_alter_favorites_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_at', 'priority'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='goals',
            name='current_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='target_value',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='Изображение'),
        ),
    ]
