# Generated by Django 6.0.4 on 2026-08-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plapp', '0004_alter_tasks_options_alter_goals_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='goals',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plapp.task_categories', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='goal_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_links', to='plapp.task_categories', verbose_name='Категория')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='plapp.goals', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Категория цели',
                'verbose_name_plural': 'Категории целей',
                'unique_together': {('goal', 'category')},
            },
        ),
        migrations.AddField(
            model_name='goals',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='goals', through='plapp.goal_categories', to='plapp.task_categories', verbose_name='Категории'),
        ),
    ]
