# Generated by Django 6.0.4 on 2026-09-27 12:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plapp', '0005_finances_receipt_goals_source_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, related_name='extra_tasks', to='plapp.task_categories', verbose_name='Доп. категории'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='Historicalfinances',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('receipt', models.TextField(blank=True, max_length=100, null=True, verbose_name='Чек')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plapp.finance_categories', verbose_name='Категория')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'historical Финансовая запись',
                'verbose_name_plural': 'historical Финансы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalgoals',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('target_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цель')),
                ('current_value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Прогресс')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('achieved', 'Достигнута')], default='active', max_length=10, verbose_name='Статус')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на источник')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'historical Цель',
                'verbose_name_plural': 'historical Цели',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaltasks',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена')], default='active', max_length=10, verbose_name='Статус')),
                ('image_path', models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plapp.task_categories', verbose_name='Категория')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'historical Задача',
                'verbose_name_plural': 'historical Задачи',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
